##Game Window
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
INTERFACE_WIDTH = 200
FPS_CAP = 60

##Enemy
ENEMY_WIDTH = 50
ENEMY_DISTANCE_X = 50
ENEMY_DISTANCE_Y = 50
SPAWN_OFFSET_X = 50
SPAWN_OFFSET_Y = 50
##Player
PLAYER_WIDTH = 30
 
##Bullet
BULLET_SPEED = 1
BULLET_SIZE = 5